### ISSUE TITLE
section heeft een h2 nodig 

### ISSUE THREAD

**Issue by Yu-Jing-van-Gerwen** [nadiachaja/the-client-website#1]
een section heeft een h2 nodig maak hier een ander element van

https://github.com/nadiachaja/the-client-website/blob/7925ddee6152dbfa96f061a4c594d985da645b28/index.html#L39-L45

zie hier de documentatie :https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

kijk anders of je hier een nav van kan maken:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

**Comment by nadiachaja** [comment]
- ik heb de `section `aangepast   [ wolkje ](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L17-L18) [muis](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L30-L32)  [menu ](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L36-L42)
- ik heb het menu een [`nav`](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L36-L42) gebruikt
