### ISSUE TITLE
Layout in CSS

### ISSUE THREAD

**Issue by Robin1224** [nadiachaja/the-client-website#11]
- Het `<main>` element op je home pagina heeft een grid layout om zijn child elementen op een rijtje te zetten. Omdat je hier maar 1 kolom gebruikt, kun je denk ik beter een flexbox layout toepassen. Dit is een simpelere oplossing met hetzelfde resultaat. 

- Bij de grid layout op je `<main>` element heb je ook een rij te veel. De eerste rij is leeg en daarom kun je deze beter weglaten. Als je hier flexbox gebruikt heb je dit probleem ook al opgelost.

- Op de menu pagina gebruik je op de `<body>` ook weer een grid layout gebruikt met maar 1 kolom. Ook hier is het aangeraden om een flexbox layout toe te passen.

- Op de menu pagina gebruik je ook een `<main>` element met een grid layout. Hier is niks mis mee, maar je hebt wel een rij te veel. De eerste rij is leeg en daarom overbodig.

- Op de menu pagina heb je ook een `<footer>` element met een grid layout. Deze is hier niet nodig, omdat het element maar 1 child heeft. Je kunt deze child beter positioneren met een property als float, of align-self. ([Meer info](https://developer.mozilla.org/en-US/docs/Web/CSS/float))

Met
@julia-stevens

**Comment by nadiachaja** [comment]
Dankjewel. Ik ga de volgorde keer beter kijken welke layout ik zal gebruiken. 

Ik heb mijn [menu ](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L14-L119)wat verandert en heb nu [flex](https://github.com/nadiachaja/the-client-website/blob/main/styles/styles.css#L26-L33) gebruikt. Het menu staat op dezelfde pagina als de homepagina
