### ISSUE TITLE
Menu als nieuwe pagina ipv in de pagina

### ISSUE THREAD

**Issue by lisagjh** [nadiachaja/the-client-website#12]
Je menu word nu geopend als nieuwe pagina. Ik heb hier onder de code verzameld die ik vorig jaar heb gebruikt voor een vergelijkbaar uitklapbaar menu, misschien heb je er wat aan. Als je er niet uit komt of vragen hebt, stuur me gewoon een berichtje!

Voorbeeld website:
https://lisagjh.github.io/all-human-accessible-website/

Repo:
https://github.com/lisagjh/all-human-accessible-website

**Comment by nadiachaja** [comment]
Ik heb een [menu](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L14-L119) op de homepagina gezet

Zo zit [het](https://nadiachaja.github.io/the-client-website/) eruit
