### ISSUE TITLE
Gebruik op links zonder text een aria-label

### ISSUE THREAD

**Issue by lisagjh** [nadiachaja/the-client-website#13]
https://github.com/nadiachaja/the-client-website/blob/d4f6f81830ffa1d653f883e3d352dd5c6de44271/index.html#L44C15-L48C19

Om de toegankelijkheid te verbeteren kun je op links zonder tekst een `aria-labal` gebruiken. Op deze manier krijgen gebruikers die bijvoorbeeld een screenreader gebruiken meer informatie over wat de link is.

Hier kan je meer lezen over aria-label:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

**Comment by nadiachaja** [comment]
dankjewel 
ik ga dit zeker vaker gebruiken 
ik heb nu bij de button een [aria-labe](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L294)l gezet
