### ISSUE TITLE
Goed gebruik van rem

### ISSUE THREAD

**Issue by lisagjh** [nadiachaja/the-client-website#14]
https://github.com/nadiachaja/the-client-website/blob/d4f6f81830ffa1d653f883e3d352dd5c6de44271/styles/styles.css#L52-L55

Erg goed dat je vaak rem gebruikt! Ik zie dat je vooral voor font-size nog wel px gebruikt, maar daar kan je ook gewoon rem voor gebruiken. 1rem = 16px ! Goed bezig

**Comment by nadiachaja** [comment]
voor de volgende keer ga ik meer rem gebruiken in plaats van px  voor  de font-size
