### ISSUE TITLE
Download de background image ipv link

### ISSUE THREAD

**Issue by lisagjh** [nadiachaja/the-client-website#15]
https://github.com/nadiachaja/the-client-website/blob/d4f6f81830ffa1d653f883e3d352dd5c6de44271/styles/styles.css#L7-L17

Voor de background image gebruik je nu een link van een andere website. Deze website laad erg traag, waardoor de image hier ook niet altijd snel laad. Probeer de image te downloaden (als svg) of uit de figma te exporteren.

**Comment by nadiachaja** [comment]
ik heb de achtergrond als [svg](https://github.com/nadiachaja/the-client-website/blob/main/styles/styles.css#L9) erin gezet
