### ISSUE TITLE
png muis in plaats van svg

### ISSUE THREAD

**Issue by lisagjh** [nadiachaja/the-client-website#16]
https://github.com/nadiachaja/the-client-website/blob/d4f6f81830ffa1d653f883e3d352dd5c6de44271/index.html#L35-L37

Probeer de muis ook als SVG in te laden, dan behoud je de kwalitiet. 
Doordat de achtergrond wel een SVG is, lijkt de muis nu een beetje vaag. 

png en svg verschillen:
https://www.adobe.com/creativecloud/file-types/image/comparison/png-vs-svg.html#:~:text=SVGs%20offer%20lossless%20compression%20%E2%80%94%20which,be%20larger%20than%20an%20SVG.

**Comment by nadiachaja** [comment]
ik heb de muis als een [svg](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L35-L37) erin gezet
