### ISSUE TITLE
Issue Client Website html

### ISSUE THREAD

**Issue by FatimaZelay** [nadiachaja/the-client-website#3]
Vergeet de H's niet erin te verwerken zoals h1,  h2, h3 wanneer nodig. Hierin kan je kijken wat er nog mist en wat je nog kan bijwerken. https://validator.w3.org/nu/?doc=https%3A%2F%2Fnadiachaja.github.io%2Fthe-client-website%2F

**Comment by nadiachaja** [comment]
Ik heb een [h1](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L18) erin verwerkt
