### ISSUE TITLE
Issue The-Client-Website

### ISSUE THREAD

**Issue by OFRqq** [nadiachaja/the-client-website#5]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fnadiachaja.github.io%2Fthe-client-website%2F

-lijn 23 maak je gebruik van </br> dit is niet nodig
-lijn 40 en 31 <button> zit hier in de <a>, button moet buiten de <a> zitten zoals = <button><a></button>
-lijn 36 in de <img src="..." heb je een spatie (<img src="assets/Group 12.png" )

-bij sections maak je gebruik van een heading, H2-H6.
wel een beetje onduidelijk met sommige 

verder ziet je html er prima uit!

**Comment by nadiachaja** [comment]
- `[</br>](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L18)` eruit gehaald
- `[<button>](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L37-L41)` weggehaald 
- spatie weggehaald bij [`<img src="..."`](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L31)
