### ISSUE TITLE
Review Prototype

### ISSUE THREAD

**Issue by Robinwouterson** [nadiachaja/the-client-website#6]
Review!

Prototype in HTML:

- https://validator.w3.org/ geeft  errors en waarschuwingen tijdens checken.
- Tags zijn incompleet op regel 23 en 31 ( 'br'  en 'a href' tags)
- De website (zonder css) is gedeelteijk goed opgezet, maar er zijn verbeterpunten. In de index.html en menu.html mis ik tags als <header> en <footer>.

Prototype ontwerp:
- het ontwerp is responsive

Visuele Hiërarchie:

De grootte, kleur, vorm en positie zijn op orde. Er zou eigenlijk meer Links of content in moeten om het allemaal goed te beoordelen.

**Comment by nadiachaja** [comment]
- [`br`](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L18)
- [`a`](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L37-L41)

- menu.html [`footer`](https://github.com/nadiachaja/the-client-website/blob/main/menu.html#L85-L91)
