### ISSUE TITLE
Code Review | Sprint 2 Week 1 | Amber & Julia

### ISSUE THREAD

**Issue by julia-stevens** [nadiachaja/the-client-website#7]
Code Review | Sprint 2 Week 1 | Amber & Julia

https://validator.w3.org/nu/?doc=https%3A%2F%2Fnadiachaja.github.io%2Fthe-client-website%2F
De HTML validator geeft een aantal errors aan: 
1. <img width="825" alt="image" src="https://github.com/user-attachments/assets/b79443f5-7e20-40a2-84b2-ff17f07882b6">

https://github.com/nadiachaja/the-client-website/blob/7925ddee6152dbfa96f061a4c594d985da645b28/index.html#L23
Hier heb je 2x een /br. Om een break te schrijven in HTML, gebruik je: `<br />`, zie: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

2. <img width="659" alt="image" src="https://github.com/user-attachments/assets/409dc97a-673b-451c-a3b0-79d5fd83ec83">
De `button` staat nu in je `a` tag, dit is eigenlijk overbodig. Je kunt als je doorverwijst naar een andere pagina, alleen `a` gebruiken 

3. <img width="564" alt="image" src="https://github.com/user-attachments/assets/48cef6ec-99fe-4791-bbe7-e5a9dc35e5d6">
De gebruikt `section`, alleen ontbreekt hier nog een heading. Als je section gebruikt, hoort er altijd een heading bij, zie MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

4. <img width="683" alt="image" src="https://github.com/user-attachments/assets/008349d6-2475-4b4d-a696-a5bb992222a2">
Let op dat je bij de benaming van de afbeeldingen geen spatie gebruikt. Gebruik hier bijvoorbeeld een streepje (-).

**Comment by ambersr** [comment]
Ik heb de CSS code even uitgezet om te testen of de structuur van de pagina er goed uitziet. Je hebt een goede logische opbouw, de tekstvlak met let's do it en de button staat boven de muis en de hamburger menu staat onderaan de pagina net zoals in het design. Ziet er goed uit!

**Comment by julia-stevens** [comment]
Review Prototype Ontwerp 
1. Het ontwerp is al uitgebreid vormgegeven in Figma, hierin lijkt niks te ontbreken
2. Het lijkt erop dat de pagina's niet responsive zijn. Wellicht dat het alleen een app is? Anders misschien interessant om nog ontwerpen te maken voor verschillende scherm breedtes? 
3. Het lijkt erop dat er nog geen viewport is toegevoegd aan het ontwerp, misschien kun je dit nog doen? 
4. Er is duidelijk rekening gehouden met visuele hiërarchie. Er zijn veel verschillende kleuren, groottes, witruimtes, etc.

**Comment by julia-stevens** [comment]
Je hebt gebruikt gemaakt van `main` en `sections`

Let wel op dat je bij een `section` altijd een heading moet gebruiken: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

https://github.com/nadiachaja/the-client-website/blob/7925ddee6152dbfa96f061a4c594d985da645b28/index.html#L39-L45
Je gebruikt hier `section` voor een menu, misschien kun je hier beter `nav` gebruiken? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

https://github.com/nadiachaja/the-client-website/blob/7925ddee6152dbfa96f061a4c594d985da645b28/index.html#L35-L37
Hier heb je `section` gebruikt om een afbeeldingen in te plaatsen, misschien is `figure` hier een beter oplossingen: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure

**Comment by nadiachaja** [comment]
- `br` goed neergezet 
- de `button` bij lessons heb ik alleen de [`a`](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L26) neergezet 
- `section` bij allemaal opgelost of ander element gebruikt [wolkje,](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L17-L18) [muis](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L30-L32) en [menu ](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L36-L42)
- de [spatie](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L31) weggehaald 
- er zijn geen [errors ](https://validator.w3.org/nu/#textarea)meer 
 
- ik heb de muis en het tekstwolkje samengevoegd en de class [info ](https://github.com/nadiachaja/the-client-website/blob/main/styles/styles.css#L84-L90)
