### ISSUE TITLE
Navigatie (menu.html) niet in een apart bestand zetten

### ISSUE THREAD

**Issue by joostf** [nadiachaja/the-client-website#9]
Het menu wat verschijnt als je op het menu icoontje klikt, kan je in de index.html zelf zetten.

Gebruik hiervoor deze structuur:

```html
<nav>
  <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/contact.html">Contact</a></li>
    <li><a href="/over.html">Over deze website</a></li>
  </ul>
</nav>
```

**Comment by nadiachaja** [comment]
ik heb de [nav](https://github.com/nadiachaja/the-client-website/blob/main/index.html#L42-L50) aangepast
